backend = "glx";

# Blur
blur = {
    method = "dual_kawase";
    strength = 5;
};

# Cibler uniquement st pour le blur
#blur-background-include = [
#    { class_g = "st-256color"; }
#];

# Transparence
opacity-rule = [
    "85:class_g = 'st-256color' ",
    "85:class_g = 'Emacs' "
];

inactive-opacity = 1.0;
active-opacity = 1.0;
inactive-dim = 0.35;
inactive-dim-fixed = false;
